// This file is automatically generated. Do not edit it directly.
// Supabase client for database operations, authentication, and storage
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Supabase project configuration (URL and public API key)
const SUPABASE_URL = "https://xoxxvixqyqyqjbyzdklx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhveHh2aXhxeXF5cWpieXpka2x4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwMDQwOTEsImV4cCI6MjA3NzU4MDA5MX0.3a7eeF30Qg75piM_VOJQjquBbzUOrNvQheAudIy3jiY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create and export the Supabase client with authentication settings
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Store auth tokens in browser localStorage for persistence
    storage: localStorage,
    // Keep user logged in across browser sessions
    persistSession: true,
    // Automatically refresh expired tokens
    autoRefreshToken: true,
  }
});